package com.example.fisintern_spring.controllers;


import com.example.fisintern_spring.models.BilliardTable;
import com.example.fisintern_spring.repositories.BilliardTableRepository;
import com.example.fisintern_spring.services.BilliardTableService;
import jakarta.transaction.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.List;

@Controller
@RequestMapping("/tables")
public class BilliardTableController {
    @Autowired //This means to get the bean called userRepository
    //Which is auto-generated by Spring, we will use it to handle the data
    private BilliardTableRepository tableRepository;

    @Autowired
    private BilliardTableService tableService;

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<BilliardTable> getAllUsers() {
        // This returns a JSON or XML with the users
        return tableRepository.findAll();
    }

    @GetMapping(path = "/status")
    public @ResponseBody List<BilliardTable> getTableByStatus(@RequestParam String status) {
        return tableRepository.findTableByStatus(status);
    }
}
