package com.example.fisintern_spring.controllers;


import com.example.fisintern_spring.models.Customer;
import com.example.fisintern_spring.repositories.CustomerRepository;
import com.example.fisintern_spring.services.CustomerService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping("/customer")
public class CustomerController {
    @Autowired //This means to get the bean called userRepository
    //Which is auto-generated by Spring, we will use it to handle the data
    private CustomerRepository customerRepository;

    @Autowired
    private CustomerService customerService;

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<Customer> getAllUsers() {
        // This returns a JSON or XML with the users
        return customerRepository.findAll();
    }

    @GetMapping(path = "/findbyid/{id}")
    public @ResponseBody Customer findCustomerById(@PathVariable int id) {
        // This returns a JSON or XML with the users
        return customerRepository.findById(id).get();
    }

    @PostMapping(path = "/addcustomer") // Map ONLY POST Requests
    public @ResponseBody String addNewCustomer(@RequestParam String name, @RequestParam String email) {
        return customerService.addNewCustomer(name, email);
    }
}
