package com.example.fisintern_spring.customers;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

@Controller //This means that this class is a Controller
@RequestMapping(path = "/demo") //This means URL's start with /demo (after Application path)
public class CustomersController {
    @Autowired //This means to get the bean called userRepository
    //Which is auto-generated by Spring, we will use it to handle the data
    private CustomersRepository customersRepository;

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<Customers> getAllUsers() {
        // This returns a JSON or XML with the users
        return customersRepository.findAll();
    }
}
