package com.example.fisintern_spring.student;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.List;

@Controller //This means that this class is a Controller
@RequestMapping(path = "/demo") //This means URL's start with /demo (after Application path)
public class StudentController {
    @Autowired //This means to get the bean called userRepository
    //Which is auto-generated by Spring, we will use it to handle the data
    private StudentRepository studentRepository;

    @GetMapping(path = "/findbyname")
    public @ResponseBody Iterable<Student> findByName(@RequestParam String name) {
        return studentRepository.findStudentByName(name);
    }

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<Student> getAllUsers() {
        // This returns a JSON or XML with the users
        return studentRepository.findAll();
    }

    @GetMapping(path = "/findclass")
    public @ResponseBody Iterable<Object[]> findClass() {
        return studentRepository.findStudentClassData();
    }

    @PostMapping(path = "/updateaverage")
    public @ResponseBody String updateAverage(@RequestParam Integer student_id) {
        Double average = studentRepository.findAverageScore(student_id);
        return studentRepository.updateScore(average.intValue(), student_id);
    }
}
