package com.example.fisintern_spring.student;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Controller //This means that this class is a Controller
@RequestMapping(path = "/demo") //This means URL's start with /demo (after Application path)
public class StudentController {
    @Autowired //This means to get the bean called userRepository
    //Which is auto-generated by Spring, we will use it to handle the data
    private StudentRepository studentRepository;

    @GetMapping(path = "/findbyname")
    public @ResponseBody Iterable<Student> findByName(@RequestParam String name) {
        return studentRepository.findStudentByName(name);
    }

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<Student> getAllUsers() {
        // This returns a JSON or XML with the users
        return studentRepository.findAll();
    }

    @GetMapping(path = "/findclass")
    public @ResponseBody Iterable<Object[]> findClass() {
        return studentRepository.findStudentClassData();
    }

    @GetMapping(path = "/findaverage")
    public @ResponseBody Double findAverage(@RequestParam Integer student_id) {
        return studentRepository.findAverageScore(student_id);
    }

    @Transactional
    @PatchMapping(path = "/updateaverage")
    public @ResponseBody String updateAverage(@RequestParam Integer student_id) {
        Double score = studentRepository.findAverageScore(student_id);
        studentRepository.updateScore(score.intValue(), student_id);
        return "Updated";
    }
}
